#!perl

# This plugin must at the end in the plugins file.

sub hook_plugins_loaded(@) {
    call_hooks("deposit_methods", \my $message, \my %hash);
    if (keys %hash) {
        HELP1 "deposit <amount> <method>" => "Add money to an account";
    } else {
        HELP1 "deposit <amount>" => "Add money to an account";
    }
}

sub command :Tab(deposit) ($self, $cart, $command, @) {
    $command eq 'deposit' or return NEXT;

    my $prompt = "Amount to deposit into your account";
    call_hooks("deposit_command", \$prompt, $self->{alternatives} = []);

    return $prompt, \&amount;
}

sub amount :Tab(13.37,42) ($self, $cart, $input, @) {
    for my $sub (@{ $self->{alternatives} }) {
        my @rv = $sub->(undef, $cart, $input);
        return @rv if $rv[0] != NEXT;
    }

    $self->{amount} = my $amount = parse_amount($input)
        or return REJECT, "Invalid input.";

    call_hooks("deposit_methods", \my $message, $self->{deposit_methods} = {});

    return $message . "How are we receiving this $amount?", \&how
        if keys %{ $self->{deposit_methods} };

    $cart
        ->add(+$amount, "Deposit", { is_deposit => 1 })
        ->add_contra("-deposits/other", -$amount, "Deposited by \$you");

    return ACCEPT;
}

sub how :Tab(&how_tab) ($self, $cart, $input, @) {
    my $method = \$self->{method};

    if (not $$method) {
        # "How are we receiving...?"
        $$method = $self->{deposit_methods}{$input}
            or return REJECT, "'$input' is not a valid answer.";

        $$method->{_key} = $input;
        $$method->{contra} ||= $input eq 'cash' ? '-cash' : "-deposits/$input";
    } else {
        # Follow-up prompt
        push @{ $$method->{answers} }, $input;
    }

    my $prompts = $$method->{prompts} // [];
    if (@$prompts) {
        return shift @$prompts, \&how;
    }

    my $desc = sprintf $$method->{description}, @{ $$method->{answers} };

    $cart
        ->add(+$self->{amount}, $desc, { is_deposit => 1, method => $$method->{_key} })
        ->add_contra($$method->{contra}, -$self->{amount}, "$desc by \$you");

    return ACCEPT;
}

sub how_tab($self, @) {
    return keys %{ $self->{deposit_methods} };
}

