#!perl

HELP1 "help2" => "Advanced usage instructions";

use List::Util qw(max);

my $bold = "\e[1m";
my $dim = "\e[2m";
my $underline = "\e[4m";
my $off = "\e[0m";

sub _print_table($hide_arguments, $hash) {
    my @output;

    for my $command (sort keys %$hash) {
        my $display = $command;
        $display =~ s/ .*// if $hide_arguments;

        my $length = length $display =~ s/[<>]//rg;

        $display =~ s/</$underline/g;
        $display =~ s/>/$off/g;

        push @output, [ $length, $display, $hash->{$command} ];
    }

    my $width = max(map $_->[0], @output);
    foreach my $line (@output) {
        my ($length, $display, $description) = @$line;
        $display .= " " x ($width - $length);
        say sprintf "  %s  %s", $display, $description;
    }
}

sub command :Tab(help,help2,wtf,omgwtfbbq) ($self, $cart, $command, @) {
    return NEXT if $command !~ /^(?:help2?|wtf|omgwtfbbq)$/;

    if ($command eq 'help2') {
        say "\n${bold}Advanced commands: ${off} (press <Enter> or use space separated arguments)";
        _print_table 0, { %::HELP1{ grep / /, keys %::HELP1 }, %::HELP };
    } else {
        say "\n${bold}Basic commands: ${off} ${dim}(press <Enter> after a command)${off}";
        _print_table 1, \%::HELP1;

        print "\n";
        print "- Scan one or more barcodes (or type ${underline}productID${off}s) to buy products.\n"
            if defined &RevBank::Plugin::products::command;
        print "- Complete a transaction with ${underline}account${off} (i.e. enter your name).\n"
            if defined &RevBank::Plugin::users::command;
    }

    return ACCEPT;
}
